---
title: "P8105 Homework 5"
author: 'Zanis Fang, UID: ZF2213'
date: "11/1/2018"
output: github_document
---

```{r setup, include=FALSE, message = FALSE}

knitr::opts_chunk$set(
	echo = TRUE,
	fig.width = 8,
	fig.asp = .618
)	

library(tidyverse)

```

## Problem 1

```{r spaghetti_plot, message = FALSE}
# read file name
tibble(id = list.files("./data", full.names = TRUE)) %>%
	# read tables and nest into dataframe
	mutate(data = map(.x = id, .f = ~read_csv(.x))) %>% 
	# unnest
	unnest() %>% 
	# get the sample identifier and group type
  mutate(id = str_extract(id, "(con|exp)_\\d{2}"),
  			 group_type = str_extract(id, "con|exp"),
  			 group_type = fct_recode(group_type,
  			 												"Control" = "con",
  			 												"Experiment"  = "exp")
  			 ) %>%
	# tidy the dataset
	gather(key = "week", value = "values", "week_1":"week_8") %>% 
	# make week numeric
	mutate(week = as.numeric(str_extract(week, "[1-8]"))) %>% 
	ggplot(aes(x = week, y = values, group = id, color = group_type)) +
	  geom_line() + 
	  geom_point() +
	  labs(
	  	x = "Week",
	  	y = "Values",
	  	color = "Group",
	  	title = "A Longitudinal Study"
	  ) +
	  scale_x_continuous(breaks = c(1:8)) +
	  theme(legend.position = "bottom")
    

```

Experimental group increase over time and control group remains unchanged overtime.

## Problem 2

Data tidying:

```{r problem2_tidying}

# read data from github repo
homicide_raw <- read_csv("https://raw.githubusercontent.com/washingtonpost/data-homicides/master/homicide-data.csv") %>% 
	# create city_state variable
	unite(col = "city_state", city:state, sep = ", ", remove = FALSE)

```

Get number of homicides:

```{r unsolved_homicides}
unsolved_homicide <- homicide_raw %>% 
	# get city total first
	group_by(city_state) %>% 
	mutate(city_total = n()) %>% 
	# then get boolean about whether solved
	group_by(solved = disposition %in% c("Closed by arrest"),
					 # also keep the two variables
					 city_state, city_total) %>%
	# get subtotal
	summarize(subtotal = n()) %>% 
	# get only unsolved
	filter(solved == FALSE) %>% ungroup()
	
```

Baltimore, MD:

```{r prop_test_baltimore}
# get data from Baltimore, MD
baltimore_homicide <- unsolved_homicide %>% filter(city_state == "Baltimore, MD")
# make prop.test results in a table
broom::tidy(
	# proportion test
	prop.test(
		# unsolved...
		baltimore_homicide$subtotal,
		# ...among all cases
		baltimore_homicide$city_total)
	)

```

All states:

```{r full_prop_test}
# statistics for proportion test
proptest_homicide <- unsolved_homicide %>% 
	# map prop.test to all states
	mutate(prop_test = map2(.x = subtotal, .y = city_total,
													~broom::tidy(prop.test(.x, .y))
												 	)) %>%
	unnest() %>%
	# select necessary columns for plotting
	select(city_state, estimate, conf.low, conf.high)

# plot
proptest_homicide %>%
	ggplot(aes(x = reorder(city_state, estimate), y = estimate)) +
	  # add points and errorbar
	  geom_point() +
	  geom_errorbar(aes(ymin = conf.low, ymax = conf.high)) +
	  # label axis and change themes
	  labs(
	  	x = "Cities",
	  	y = "Estimates with Confidence Intervals",
	  	title = "Proportion of unsolved cases"
	  ) +
	  theme(
	  	axis.text.x = element_text(angle = 90)
	  )

```



